import json
import optparse
import os
import re

def extract_demo_data(transcript_path, account_id):
    with open(transcript_path, 'r', encoding='utf-8') as f:
        transcript = f.read()

    # Simple logic to simulate extraction. In a real system, this would be an LLM call.
    # We will look for some keywords in our specific sample transcripts.
    
    company_name = "Unknown"
    company_match = re.search(r"calling from (.*?) demo line", transcript)
    if company_match:
        company_name = company_match.group(1)

    services_supported = []
    if "sprinkler" in transcript.lower():
        services_supported.append("sprinkler")
    if "fire alarm" in transcript.lower():
        services_supported.append("fire alarm")

    emergency_definition = []
    if "sprinkler leak" in transcript.lower():
        emergency_definition.append("sprinkler leak")
    if "fire alarm issue" in transcript.lower():
        emergency_definition.append("fire alarm issue")

    questions = []
    if "standard business hours" in transcript:
        questions.append("Confirm exact business hours and timezone")
    if "ServiceTrade" in transcript:
        questions.append("Confirm ServiceTrade integration workflow")

    memo = {
        "account_id": account_id,
        "company_name": company_name,
        "business_hours": {
            "days": None,
            "start": None,
            "end": None,
            "timezone": None
        },
        "office_address": None,
        "services_supported": services_supported,
        "emergency_definition": emergency_definition,
        "emergency_routing_rules": ["Transfer emergencies to dispatch"],
        "non_emergency_routing_rules": ["Take message during office hours"],
        "call_transfer_rules": {
            "transfer_timeout": 60,
            "retry_attempts": 0,
            "what_to_say_if_fails": "I'm sorry, I'm having trouble connecting you. Let me try another way."
        },
        "integration_constraints": [],
        "after_hours_flow_summary": "Collect name, phone, address for emergencies; take message for others.",
        "office_hours_flow_summary": "Greet, ask purpose, collect details, route/transfer.",
        "questions_or_unknowns": questions,
        "notes": "Generated from demo call transcript."
    }

    # Agent Spec
    agent_spec = {
        "agent_name": f"Clara - {company_name}",
        "version": "v1",
        "voice": "calm professional",
        "system_prompt": "", # Will be generated by another script
        "key_variables": {
            "timezone": "unknown",
            "business_hours": "unknown",
            "office_address": "unknown",
            "emergency_routing": "dispatch"
        },
        "tool_invocation_placeholders": [
            "create_service_ticket",
            "trigger_transfer"
        ],
        "call_transfer_protocol": "Transfer to dispatch if emergency",
        "fallback_protocol": "Apologize and inform dispatch follow up"
    }

    # Save outputs
    output_dir = os.path.join("outputs", "accounts", account_id, "v1")
    os.makedirs(output_dir, exist_ok=True)

    with open(os.path.join(output_dir, "account_memo.json"), 'w', encoding='utf-8') as f:
        json.dump(memo, f, indent=4)
    
    with open(os.path.join(output_dir, "agent_spec.json"), 'w', encoding='utf-8') as f:
        json.dump(agent_spec, f, indent=4)

    print(f"v1 configuration generated for {account_id}")
    
    # Mock Task Tracker Integration
    create_task_item(account_id, company_name)

def create_task_item(account_id, company_name):
    task_file = os.path.join("outputs", "task_tracker.json")
    tasks = []
    if os.path.exists(task_file):
        with open(task_file, 'r') as f:
            tasks = json.load(f)
    
    new_task = {
        "task_id": f"TASK-{account_id}",
        "title": f"Deploy Retell Agent for {company_name}",
        "status": "Pending v2 Onboarding",
        "priority": "High",
        "account_id": account_id
    }
    tasks.append(new_task)
    
    with open(task_file, 'w') as f:
        json.dump(tasks, f, indent=4)
    print(f"Tracking item created: {new_task['task_id']}")

if __name__ == "__main__":
    parser = optparse.OptionParser()
    parser.add_option("--transcript", dest="transcript")
    parser.add_option("--account_id", dest="account_id")
    (options, args) = parser.parse_args()
    
    if options.transcript and options.account_id:
        extract_demo_data(options.transcript, options.account_id)
    else:
        print("Usage: python extract_demo_data.py --transcript <path> --account_id <id>")
